version: '3.7'
services:
  youtube-dl:
    # alternative image: kijart/youtube-dl
    # youtube.conf is copied to image during build
    image: youtube-dl
    container_name: objYouTube
    # (required) WORKDIR specifies the download folder
    volumes:
      - ${WORKDIR}:/media:rw
    # (optional) --batch-file batchfile.txt
    # (optional) --dateafter 20200223
    # (required) URL can be either a video or playlist
    command: ${BATCH} ${AFTER} ${URL}
